export const SEHIR_ILCE: Record<string, string[]> = {
  istanbul: ['kadikoy', 'besiktas', 'sisli', 'fatih', 'uskudar', 'maltepe', 'pendik', 'umraniye', 'bagcilar', 'bahcelievler', 'beyoglu', 'sariyer', 'eyup', 'gaziosmanpasa', 'kagithane', 'kartal', 'kucukcekmece', 'sultanbeyli', 'tuzla', 'avcilar', 'esenyurt', 'basaksehir', 'atasehir', 'beykoz', 'beylikduzu', 'cekmekoy', 'esenler', 'sultangazi', 'zeytinburnu', 'adalar', 'arnavutkoy', 'bayrampasa', 'buyukcekmece', 'catalca', 'sile', 'silivri'],
  ankara: ['cankaya', 'kecioren', 'mamak', 'yenimahalle', 'etimesgut', 'sincan', 'altindag', 'pursaklar', 'golbasi', 'polatli', 'haymana', 'beypazari', 'cubuk', 'kazan', 'akyurt', 'elmadağ', 'kahramankazan', 'bala', 'camlidere', 'evren', 'gudul', 'kalecik', 'kizilcahamam', 'nallihan', 'sereflikoçhisar', 'ayas'],
  izmir: ['konak', 'karsiyaka', 'bornova', 'buca', 'cigli', 'narlidere', 'gaziemir', 'bayrakli', 'cesme', 'aliaga', 'bergama', 'dikili', 'foca', 'kemalpasa', 'menemen', 'odemis', 'seferihisar', 'selcuk', 'tire', 'torbali', 'urla', 'balcova', 'bayindir', 'beydağ', 'guzelbahce', 'karaburun', 'kinik', 'kiraz', 'menderes'],
  bursa: ['nilufer', 'osmangazi', 'yildirim', 'inegol', 'gemlik', 'mudanya', 'gursu', 'kestel', 'mustafakemalpasa', 'iznik', 'karacabey', 'orhangazi', 'yenisehir', 'buyukorhan', 'harmancik', 'keles', 'orhaneli'],
  antalya: ['muratpasa', 'kepez', 'konyaalti', 'alanya', 'manavgat', 'serik', 'kas', 'kemer', 'finike', 'gazipasa', 'kumluca', 'akseki', 'aksu', 'dosemealtı', 'elmali', 'gundogmus', 'ibradı', 'kale'],
  adana: ['seyhan', 'yuregir', 'cukurova', 'saricam', 'kozan', 'ceyhan', 'karaisali', 'imamoglu', 'pozanti', 'saimbeyli', 'tufanbeyli', 'yumurtalik', 'aladağ'],
  konya: ['selcuklu', 'meram', 'karatay', 'eregli', 'beysehir', 'aksehir', 'cihanbeyli', 'cumra', 'doganhisar', 'ilgin', 'karapinar', 'kulu', 'seydisehir', 'akoren', 'altinekin', 'bozkir', 'derbent', 'derebucak', 'emirgazi', 'guneysinir', 'hadim', 'halkapinar', 'huyuk', 'kadinhani', 'sarayonu', 'taskent', 'tuzlukçu', 'yalihuyuk', 'yunak'],
  gaziantep: ['sahinbey', 'sehitkamil', 'islahiye', 'nizip', 'oguzeli', 'nurdagi', 'araban', 'karkamis', 'yavuzeli'],
  mersin: ['yenisehir', 'mezitli', 'toroslar', 'akdeniz', 'tarsus', 'erdemli', 'silifke', 'anamur', 'gulnar', 'mut', 'aydincik', 'bozyazi', 'camliyayla'],
  kayseri: ['melikgazi', 'kocasinan', 'talas', 'develi', 'yahyali', 'bunyan', 'hacilar', 'incesu', 'akkisla', 'felahiye', 'ozvatan', 'pinarbaşı', 'sariz', 'tomarza', 'yesilhisar'],
  eskisehir: ['tepebasi', 'odunpazari', 'alpu', 'inonu', 'mahmudiye', 'seyitgazi', 'sivrihisar', 'beylikova', 'gursu', 'han', 'mihalgazi', 'mihalıccık', 'saricakaya'],
  trabzon: ['ortahisar', 'akcaabat', 'arakli', 'arsin', 'besikduzu', 'caykara', 'macka', 'of', 'tonya', 'vakfikebir', 'yomra', 'carsibasi', 'dernekpazari', 'duzkoy', 'hayrat', 'koprubasi', 'pelitli', 'surmene'],
  samsun: ['ilkadim', 'canik', 'atakum', 'tekkeköy', 'bafra', 'carsamba', 'havza', 'kavak', 'terme', 'vezirkopru', 'alaçam', 'asarcik', 'ayvacik', 'ladik', 'salıpazari', 'yakakent'],
  denizli: ['pamukkale', 'merkezefendi', 'buldan', 'civril', 'tavas', 'acipayam', 'honaz', 'saraykoy', 'babadag', 'baklan', 'bekilli', 'beyagac', 'bozkurt', 'cameli', 'cardak', 'guney', 'kale', 'serinhisar'],
  balikesir: ['altieylul', 'karesi', 'bandirma', 'edremit', 'ayvalik', 'burhaniye', 'gonen', 'havran', 'sindirgi', 'susurluk', 'bigadic', 'dursunbey', 'gomec', 'ıvrindi', 'kepsut', 'manyas', 'marmara', 'savastepe'],
  malatya: ['battalgazi', 'yesilyurt', 'akcadag', 'darende', 'dogansehir', 'hekimhan', 'arapgir', 'arguvan', 'doganyol', 'kale', 'kuluncak', 'pütürge', 'yazihan'],
  kahramanmaras: ['dulkadiroglu', 'oniksubat', 'afsin', 'elbistan', 'goksun', 'pazarcik', 'turkoglu', 'andirin', 'caglayancerit', 'ekinozu', 'nurhak'],
  erzurum: ['yakutiye', 'aziziye', 'palandoken', 'oltu', 'horasan', 'ispir', 'narman', 'askale', 'cat', 'hinis', 'karayazi', 'koprukoy', 'olur', 'pazaryolu', 'senkaya', 'tekman', 'tortum', 'uzundere'],
  van: ['ipekyolu', 'tusba', 'edremit', 'ercis', 'gevas', 'gurpinar', 'muradiye', 'baskale', 'caldiran', 'catak', 'ozalp', 'saray'],
  diyarbakir: ['baglar', 'kayapinar', 'yenisehir', 'sur', 'ergani', 'bismil', 'cinar', 'silvan', 'cermik', 'cungus', 'dicle', 'egil', 'hani', 'hazro', 'kulp', 'lice'],
  sanliurfa: ['haliliye', 'eyyubiye', 'karakopru', 'siverek', 'birecik', 'ceylanpinar', 'harran', 'viransehir', 'bozova', 'halfeti', 'hilvan', 'suruc'],
  manisa: ['sehzadeler', 'yunusemre', 'akhisar', 'alasehir', 'gordes', 'kula', 'salihli', 'soma', 'turgutlu', 'demirci', 'golmarmara', 'kirkagac', 'köprübaşı', 'sarigöl', 'saruhanli', 'selendi'],
  aydin: ['efeler', 'nazilli', 'kusadasi', 'didim', 'soke', 'incirliova', 'germencik', 'cine', 'bozdogan', 'buharkent', 'karacasu', 'karpuzlu', 'kocarli', 'kuyucak', 'sultanhisar', 'yenipazar'],
  tekirdag: ['corlu', 'ergene', 'hayrabolu', 'malkara', 'muratli', 'saray', 'suleymanpasa', 'kapakli', 'marmara-ereglisi', 'sarkoy'],
  sakarya: ['adapazari', 'akyazi', 'arifiye', 'erenler', 'ferizli', 'geyve', 'hendek', 'karasu', 'sapanca', 'serdivan', 'karapurçek', 'kaynarca', 'kocaali', 'pamukova', 'sogutlu', 'tarakli'],
  kocaeli: ['izmit', 'gebze', 'golcuk', 'darica', 'derince', 'basiskele', 'cayirova', 'kandira', 'karamursel', 'kartepe', 'dilovasi', 'korfez'],
  hatay: ['antakya', 'iskenderun', 'dortyol', 'reyhanli', 'kirikhan', 'belen', 'erzin', 'hassa', 'samandağ', 'altınözü', 'kumlu', 'mandacı', 'payas', 'yayladağı'],
  mugla: ['bodrum', 'marmaris', 'fethiye', 'milas', 'datca', 'dalaman', 'koycegiz', 'ortaca', 'seydikemer', 'ula', 'yatagan', 'kavaklidere'],
  mardin: ['artuklu', 'dargecit', 'derik', 'kiziltepe', 'midyat', 'nusaybin', 'savur', 'mazidagi', 'omerli', 'yesilli'],
  afyonkarahisar: ['merkez', 'bolvadin', 'cay', 'dinar', 'emirdag', 'sandikli', 'sinanpasa', 'cobanlar', 'dazkiri', 'evciler', 'hocalar', 'ihsaniye', 'iscehisar', 'kiziloren', 'suhut', 'sultandagi'],
  isparta: ['merkez', 'egirdir', 'gelendost', 'keciborlu', 'senirkent', 'uluborlu', 'yalvac', 'aksu', 'atabey', 'gonen', 'sutculer', 'yenisarbademli'],
  bolu: ['merkez', 'gerede', 'goynuk', 'mengen', 'mudurnu', 'dörtdivan', 'kibriscik', 'seben', 'yeniçağa'],
  canakkale: ['merkez', 'ayvacik', 'biga', 'can', 'eceabat', 'ezine', 'gelibolu', 'lapseki', 'bayramic', 'bozcaada', 'gokceada', 'yenice'],
  edirne: ['merkez', 'enez', 'havsa', 'ipsala', 'kesan', 'uzunkopru', 'lalapasa', 'meric', 'suloglu'],
  kirklareli: ['merkez', 'babaeski', 'luleburgaz', 'pinarhisar', 'vize', 'demirkoy', 'kofcaz', 'pehlivankoy'],
  kirikkale: ['merkez', 'delice', 'karakecili', 'keskin', 'yahsihan', 'bahsili', 'balışeyh', 'celebi', 'sulakyurt'],
  nevsehir: ['merkez', 'acigol', 'avanos', 'derinkuyu', 'gulsehir', 'urgup', 'hacibektas', 'kozakli'],
  nigde: ['merkez', 'altunhisar', 'bor', 'ulukisla', 'ciftlik'],
  ordu: ['altinordu', 'akkus', 'fatsa', 'korgan', 'kumru', 'persembe', 'unye', 'aybasti', 'çamaş', 'çatalpinar', 'çaybaşı', 'golkoy', 'gurgentepe', 'ikizce', 'kabaduz', 'kabatas', 'mesudiye', 'ulubey'],
  rize: ['merkez', 'ardeşen', 'cayeli', 'findikli', 'of', 'pazar', 'camlihemsin', 'derepazari', 'guneysu', 'hemşin', 'ikizdere', 'iyidere', 'kalkandere'],
  sinop: ['merkez', 'ayancik', 'boyabat', 'gerze', 'dikmen', 'duragan', 'erfelek', 'sarayduzu', 'türkeli'],
  tokat: ['merkez', 'erbaa', 'niksar', 'turhal', 'zile', 'almus', 'artova', 'basciftlik', 'pazar', 'resadiye', 'sulusaray', 'yesilyurt'],
  usak: ['merkez', 'banaz', 'esme', 'sivasli', 'karahalli', 'ulubey'],
  yozgat: ['merkez', 'bogazliyan', 'sorgun', 'yerköy', 'akdagmadeni', 'aydincik', 'candir', 'cayiralan', 'cekerek', 'sarikaya', 'sefaatli'],
  zonguldak: ['merkez', 'caycuma', 'devrek', 'eregli', 'gokcebey', 'alapli', 'kilimli', 'kozlu'],
  agri: ['merkez', 'dogubayazit', 'eleskirt', 'patnos', 'tutak', 'diyadin', 'hamur', 'taslicay'],
  aksaray: ['merkez', 'eskil', 'ortakoy', 'sultanhani', 'agackoy', 'gulagac', 'guliesren', 'sariyahsi'],
  amasya: ['merkez', 'merzifon', 'suluova', 'tasova', 'göynücek', 'gümüşhacıköy', 'hamamözü'],
  ardahan: ['merkez', 'cildir', 'gole', 'posof', 'damal', 'hanak'],
  artvin: ['merkez', 'ardanuc', 'arhavi', 'borcka', 'hopa', 'savsat', 'murgul', 'yusufeli'],
  bartin: ['merkez', 'amasra', 'kurucasile', 'ulus'],
  batman: ['merkez', 'besiri', 'kozluk', 'sason', 'gercus', 'hasankeyf'],
  bayburt: ['merkez', 'aydintepe', 'demirozu'],
  bilecik: ['merkez', 'bozuyuk', 'osmaneli', 'sogut', 'golpazari', 'inhisar', 'pazaryeri', 'yenipazar'],
  bingol: ['merkez', 'genc', 'karliova', 'solhan', 'adakli', 'kigi', 'yayladere', 'yedisu'],
  bitlis: ['merkez', 'adilcevaz', 'ahlat', 'tatvan', 'guroymak', 'hizan', 'mutki'],
  burdur: ['merkez', 'bucak', 'golhisar', 'tefenni', 'aglasiun', 'altinyayla', 'cavdir', 'celtikci', 'karamanli', 'kemer', 'yesilova'],
  corum: ['merkez', 'alaca', 'iskilip', 'osmancik', 'sungurlu', 'bayat', 'bogazkale', 'dodurga', 'kargi', 'lacin', 'mecitözü', 'oguzlar', 'ugurludag'],
  duzce: ['merkez', 'akcakoca', 'golyaka', 'kaynasli', 'cumayeri', 'cilimli', 'gumusova', 'yigilca'],
  elazig: ['merkez', 'baskil', 'keban', 'palu', 'agin', 'aricak', 'karakocan', 'kovancilar', 'maden', 'sivrice'],
  erzincan: ['merkez', 'ilic', 'kemah', 'refahiye', 'tercan', 'cayirli', 'kemaliye', 'otlukbeli', 'üzümlü'],
  giresun: ['merkez', 'bulancak', 'espiye', 'gorele', 'tirebolu', 'alucra', 'camoluk', 'dereli', 'dogankent', 'eynesil', 'guce', 'kesap', 'piraziz', 'sebinkarahisar', 'yaglidere'],
  gumushane: ['merkez', 'kelkit', 'torul', 'kose', 'kurtun', 'siran'],
  hakkari: ['merkez', 'cukurca', 'yuksekova', 'semdinli'],
  igdir: ['merkez', 'aralik', 'tuzluca', 'karakoyunlu'],
  karabuk: ['merkez', 'safranbolu', 'yenice', 'eflani', 'eskipazar', 'ovacik'],
  karaman: ['merkez', 'ermenek', 'ayranci', 'basyayla', 'kazimkarabekir', 'sarıveliler'],
  kars: ['merkez', 'kagizman', 'sarikamis', 'selim', 'akyaka', 'arpacay', 'digor', 'susuz'],
  kastamonu: ['merkez', 'cide', 'inebolu', 'taskopru', 'tosya', 'abana', 'agli', 'arac', 'azdavay', 'bozkurt', 'daday', 'devrekani', 'doganyurt', 'hanönü', 'ihsangazi', 'kure', 'pinarbası', 'seydiler'],
  kilis: ['merkez', 'elbeyli', 'musabeyli', 'polateli'],
  kirsehir: ['merkez', 'cicekdagi', 'kaman', 'mucur', 'akcakent', 'akpinar', 'boztepe'],
  mus: ['merkez', 'bulanik', 'malazgirt', 'varto', 'haskoy', 'korkut'],
  osmaniye: ['merkez', 'bahce', 'duzici', 'kadirli', 'hasanbeyli', 'sumbas', 'toprakkale'],
  siirt: ['merkez', 'baykan', 'eruh', 'kurtalan', 'aydinlar', 'pervari', 'sirvan'],
  sirnak: ['merkez', 'cizre', 'idil', 'silopi', 'beytussebap', 'guclukonak', 'uludere'],
  sivas: ['merkez', 'divrigi', 'gurun', 'kangal', 'susehri', 'zara', 'akincilar', 'altieylul', 'dogansar', 'gemerek', 'golova', 'hafik', 'imranli', 'koyulhisar', 'saarkisla', 'ulas', 'yildizeli'],
  tunceli: ['merkez', 'hozat', 'ovacik', 'pertek', 'çemişgezek', 'mazgirt', 'nazimiye', 'pulumur'],
  adiyaman: ['merkez', 'besni', 'golbasi', 'kahta', 'celikhan', 'gerger', 'samsat', 'sincik', 'tut'],
  yalova: ['merkez', 'altinova', 'armutlu', 'cinarcik', 'termal', 'ciftlikkoy'],
};

