export const SEHIR_ILCE: Record<string, string[]> = {
  istanbul: ['kadikoy', 'besiktas', 'sisli', 'fatih', 'uskudar', 'maltepe', 'pendik', 'umraniye', 'bagcilar', 'bahcelievler', 'beyoglu', 'sariyer', 'eyup', 'gaziosmanpasa', 'kagithane', 'kartal', 'kucukcekmece', 'sultanbeyli', 'tuzla', 'avcilar', 'esenyurt', 'basaksehir', 'atasehir', 'beykoz', 'beylikduzu', 'cekmekoy', 'esenler', 'sultangazi', 'zeytinburnu'],
  ankara: ['cankaya', 'kecioren', 'mamak', 'yenimahalle', 'etimesgut', 'sincan', 'altindag', 'pursaklar', 'golbasi', 'polatli', 'haymana', 'beypazari', 'cubuk', 'kazan', 'akyurt'],
  izmir: ['konak', 'karsiyaka', 'bornova', 'buca', 'cigli', 'narlidere', 'gaziemir', 'bayrakli', 'cesme', 'aliaga', 'bergama', 'dikili', 'foca', 'kemalpasa', 'menemen', 'odemis', 'seferihisar', 'selcuk', 'tire', 'torbali', 'urla'],
  bursa: ['nilufer', 'osmangazi', 'yildirim', 'inegol', 'gemlik', 'mudanya', 'gursu', 'kestel', 'mustafakemalpasa', 'iznik', 'karacabey', 'orhangazi', 'yenisehir'],
  antalya: ['muratpasa', 'kepez', 'konyaalti', 'alanya', 'manavgat', 'serik', 'kas', 'kemer', 'finike', 'gazipasa', 'kumluca', 'akseki'],
  adana: ['seyhan', 'yuregir', 'cukurova', 'saricam', 'kozan', 'ceyhan', 'karaisali', 'imamoglu', 'pozanti'],
  konya: ['selcuklu', 'meram', 'karatay', 'eregli', 'beysehir', 'aksehir', 'cihanbeyli', 'cumra', 'doganhisar', 'ilgin', 'karapinar', 'kulu', 'seydisehir'],
  gaziantep: ['sahinbey', 'sehitkamil', 'islahiye', 'nizip', 'oguzeli', 'nurdagi', 'araban', 'karkamis'],
  mersin: ['yenisehir', 'mezitli', 'toroslar', 'akdeniz', 'tarsus', 'erdemli', 'silifke', 'anamur', 'gulnar', 'mut'],
  kayseri: ['melikgazi', 'kocasinan', 'talas', 'develi', 'yahyali', 'bunyan', 'hacilar', 'incesu'],
  eskisehir: ['tepebasi', 'odunpazari', 'alpu', 'inonu', 'mahmudiye', 'seyitgazi', 'sivrihisar'],
  trabzon: ['ortahisar', 'akcaabat', 'arakli', 'arsin', 'besikduzu', 'caykara', 'macka', 'of', 'tonya', 'vakfikebir', 'yomra'],
  samsun: ['ilkadim', 'canik', 'atakum', 'tekkeköy', 'bafra', 'carsamba', 'havza', 'kavak', 'terme', 'vezirkopru'],
  denizli: ['pamukkale', 'merkezefendi', 'buldan', 'civril', 'tavas', 'acipayam', 'honaz', 'saraykoy'],
  balikesir: ['altieylul', 'karesi', 'bandirma', 'edremit', 'ayvalik', 'burhaniye', 'gonen', 'havran', 'sindirgi', 'susurluk'],
  malatya: ['battalgazi', 'yesilyurt', 'akcadag', 'darende', 'dogansehir', 'hekimhan'],
  kahramanmaras: ['dulkadiroglu', 'oniksubat', 'afsin', 'elbistan', 'goksun', 'pazarcik', 'turkoglu'],
  erzurum: ['yakutiye', 'aziziye', 'palandoken', 'oltu', 'horasan', 'ispir', 'narman'],
  van: ['ipekyolu', 'tusba', 'edremit', 'ercis', 'gevas', 'gurpinar', 'muradiye'],
  diyarbakir: ['baglar', 'kayapinar', 'yenisehir', 'sur', 'ergani', 'bismil', 'cinar', 'silvan'],
  sanliurfa: ['haliliye', 'eyyubiye', 'karakopru', 'siverek', 'birecik', 'ceylanpinar', 'harran', 'viransehir'],
  manisa: ['sehzadeler', 'yunusemre', 'akhisar', 'alasehir', 'gordes', 'kula', 'salihli', 'soma', 'turgutlu'],
  aydin: ['efeler', 'nazilli', 'kusadasi', 'didim', 'soke', 'incirliova', 'germencik', 'cine'],
  tekirdag: ['corlu', 'ergene', 'hayrabolu', 'malkara', 'muratli', 'saray', 'suleymanpasa'],
  sakarya: ['adapazari', 'akyazi', 'arifiye', 'erenler', 'ferizli', 'geyve', 'hendek', 'karasu', 'sapanca', 'serdivan'],
  kocaeli: ['izmit', 'gebze', 'golcuk', 'darica', 'derince', 'basiskele', 'cayirova', 'kandira', 'karamursel', 'kartepe'],
  hatay: ['antakya', 'iskenderun', 'dortyol', 'reyhanli', 'kirikhan', 'belen', 'erzin', 'hassa', 'samandağ'],
  mugla: ['bodrum', 'marmaris', 'fethiye', 'milas', 'datca', 'dalaman', 'koycegiz', 'ortaca', 'seydikemer', 'ula'],
  mardin: ['artuklu', 'dargecit', 'derik', 'kiziltepe', 'midyat', 'nusaybin', 'savur'],
  afyonkarahisar: ['merkez', 'bolvadin', 'cay', 'dinar', 'emirdag', 'sandikli', 'sinanpasa'],
  isparta: ['merkez', 'egirdir', 'gelendost', 'keciborlu', 'senirkent', 'uluborlu', 'yalvac'],
  bolu: ['merkez', 'gerede', 'goynuk', 'mengen', 'mudurnu'],
  canakkale: ['merkez', 'ayvacik', 'biga', 'can', 'eceabat', 'ezine', 'gelibolu', 'lapseki'],
  edirne: ['merkez', 'enez', 'havsa', 'ipsala', 'kesan', 'uzunkopru'],
  kirklareli: ['merkez', 'babaeski', 'luleburgaz', 'pinarhisar', 'vize'],
  kirikkale: ['merkez', 'delice', 'karakecili', 'keskin', 'yahsihan'],
  nevsehir: ['merkez', 'acigol', 'avanos', 'derinkuyu', 'gulsehir', 'urgup'],
  nigde: ['merkez', 'altunhisar', 'bor', 'ulukisla'],
  ordu: ['altinordu', 'akkus', 'fatsa', 'korgan', 'kumru', 'persembe', 'unye'],
  rize: ['merkez', 'ardeşen', 'cayeli', 'findikli', 'of', 'pazar'],
  sinop: ['merkez', 'ayancik', 'boyabat', 'gerze'],
  tokat: ['merkez', 'erbaa', 'niksar', 'turhal', 'zile'],
  usak: ['merkez', 'banaz', 'esme', 'sivasli'],
  yozgat: ['merkez', 'bogazliyan', 'sorgun', 'yerköy'],
  zonguldak: ['merkez', 'caycuma', 'devrek', 'eregli', 'gokcebey'],
  agri: ['merkez', 'dogubayazit', 'eleskirt', 'patnos', 'tutak'],
  aksaray: ['merkez', 'eskil', 'ortakoy', 'sultanhani'],
  amasya: ['merkez', 'merzifon', 'suluova', 'tasova'],
  ardahan: ['merkez', 'cildir', 'gole', 'posof'],
  artvin: ['merkez', 'ardanuc', 'arhavi', 'borcka', 'hopa', 'savsat'],
  bartin: ['merkez', 'amasra', 'kurucasile', 'ulus'],
  batman: ['merkez', 'besiri', 'kozluk', 'sason'],
  bayburt: ['merkez', 'aydintepe'],
  bilecik: ['merkez', 'bozuyuk', 'osmaneli', 'sogut'],
  bingol: ['merkez', 'genc', 'karliova', 'solhan'],
  bitlis: ['merkez', 'adilcevaz', 'ahlat', 'tatvan'],
  burdur: ['merkez', 'bucak', 'golhisar', 'tefenni'],
  corum: ['merkez', 'alaca', 'iskilip', 'osmancik', 'sungurlu'],
  duzce: ['merkez', 'akcakoca', 'golyaka', 'kaynasli'],
  elazig: ['merkez', 'baskil', 'keban', 'palu'],
  erzincan: ['merkez', 'ilic', 'kemah', 'refahiye', 'tercan'],
  giresun: ['merkez', 'bulancak', 'espiye', 'gorele', 'tirebolu'],
  gumushane: ['merkez', 'kelkit', 'torul'],
  hakkari: ['merkez', 'cukurca', 'yuksekova'],
  igdir: ['merkez', 'aralik', 'tuzluca'],
  karabuk: ['merkez', 'safranbolu', 'yenice'],
  karaman: ['merkez', 'ermenek'],
  kars: ['merkez', 'kagizman', 'sarikamis', 'selim'],
  kastamonu: ['merkez', 'cide', 'inebolu', 'taskopru', 'tosya'],
  kilis: ['merkez', 'elbeyli', 'musabeyli'],
  kirsehir: ['merkez', 'cicekdagi', 'kaman', 'mucur'],
  malatya: ['battalgazi', 'yesilyurt', 'akcadag', 'darende'],
  mus: ['merkez', 'bulanik', 'malazgirt', 'varto'],
  osmaniye: ['merkez', 'bahce', 'duzici', 'kadirli'],
  siirt: ['merkez', 'baykan', 'eruh', 'kurtalan'],
  sirnak: ['merkez', 'cizre', 'idil', 'silopi'],
  sivas: ['merkez', 'divrigi', 'gurun', 'kangal', 'susehri', 'zara'],
  tunceli: ['merkez', 'hozat', 'ovacik', 'pertek'],
  adiyaman: ['merkez', 'besni', 'golbasi', 'kahta'],
  ardahan: ['merkez', 'cildir', 'gole'],
  yalova: ['merkez', 'altinova', 'armutlu', 'cinarcik', 'termal'],
};
