export const ULKELER: { slug: string; ad: string; dil: string; para: string }[] = [
  { slug: 'turkiye',        ad: 'Türkiye',          dil: 'tr', para: 'TRY' },
  { slug: 'almanya',        ad: 'Almanya',           dil: 'de', para: 'EUR' },
  { slug: 'fransa',         ad: 'Fransa',            dil: 'fr', para: 'EUR' },
  { slug: 'ingiltere',      ad: 'İngiltere',         dil: 'en', para: 'GBP' },
  { slug: 'abd',            ad: 'Amerika (ABD)',     dil: 'en', para: 'USD' },
  { slug: 'kanada',         ad: 'Kanada',            dil: 'en', para: 'CAD' },
  { slug: 'avustralya',     ad: 'Avustralya',        dil: 'en', para: 'AUD' },
  { slug: 'hollanda',       ad: 'Hollanda',          dil: 'nl', para: 'EUR' },
  { slug: 'belcika',        ad: 'Belçika',           dil: 'fr', para: 'EUR' },
  { slug: 'isvicre',        ad: 'İsviçre',           dil: 'de', para: 'CHF' },
  { slug: 'avusturya',      ad: 'Avusturya',         dil: 'de', para: 'EUR' },
  { slug: 'ispanya',        ad: 'İspanya',           dil: 'es', para: 'EUR' },
  { slug: 'italya',         ad: 'İtalya',            dil: 'it', para: 'EUR' },
  { slug: 'portekiz',       ad: 'Portekiz',          dil: 'pt', para: 'EUR' },
  { slug: 'yunanistan',     ad: 'Yunanistan',        dil: 'el', para: 'EUR' },
  { slug: 'polonya',        ad: 'Polonya',           dil: 'pl', para: 'PLN' },
  { slug: 'cek-cumhuriyeti',ad: 'Çek Cumhuriyeti',  dil: 'cs', para: 'CZK' },
  { slug: 'macaristan',     ad: 'Macaristan',        dil: 'hu', para: 'HUF' },
  { slug: 'romanya',        ad: 'Romanya',           dil: 'ro', para: 'RON' },
  { slug: 'bulgaristan',    ad: 'Bulgaristan',       dil: 'bg', para: 'BGN' },
  { slug: 'hirvatistan',    ad: 'Hırvatistan',       dil: 'hr', para: 'EUR' },
  { slug: 'sirbistan',      ad: 'Sırbistan',         dil: 'sr', para: 'RSD' },
  { slug: 'norvec',         ad: 'Norveç',            dil: 'no', para: 'NOK' },
  { slug: 'isvec',          ad: 'İsveç',             dil: 'sv', para: 'SEK' },
  { slug: 'finlandiya',     ad: 'Finlandiya',        dil: 'fi', para: 'EUR' },
  { slug: 'danimarka',      ad: 'Danimarka',         dil: 'da', para: 'DKK' },
  { slug: 'rusya',          ad: 'Rusya',             dil: 'ru', para: 'RUB' },
  { slug: 'ukrayna',        ad: 'Ukrayna',           dil: 'uk', para: 'UAH' },
  { slug: 'azerbaycan',     ad: 'Azerbaycan',        dil: 'az', para: 'AZN' },
  { slug: 'kazakistan',     ad: 'Kazakistan',        dil: 'kk', para: 'KZT' },
  { slug: 'ozbekistan',     ad: 'Özbekistan',        dil: 'uz', para: 'UZS' },
  { slug: 'turkmenistan',   ad: 'Türkmenistan',      dil: 'tk', para: 'TMT' },
  { slug: 'kirgizistan',    ad: 'Kırgızistan',       dil: 'ky', para: 'KGS' },
  { slug: 'tacikistan',     ad: 'Tacikistan',        dil: 'tg', para: 'TJS' },
  { slug: 'gurcistan',      ad: 'Gürcistan',         dil: 'ka', para: 'GEL' },
  { slug: 'ermenistan',     ad: 'Ermenistan',        dil: 'hy', para: 'AMD' },
  { slug: 'irak',           ad: 'Irak',              dil: 'ar', para: 'IQD' },
  { slug: 'iran',           ad: 'İran',              dil: 'fa', para: 'IRR' },
  { slug: 'suriye',         ad: 'Suriye',            dil: 'ar', para: 'SYP' },
  { slug: 'lübnan',         ad: 'Lübnan',            dil: 'ar', para: 'LBP' },
  { slug: 'ürdün',          ad: 'Ürdün',             dil: 'ar', para: 'JOD' },
  { slug: 'israil',         ad: 'İsrail',            dil: 'he', para: 'ILS' },
  { slug: 'misir',          ad: 'Mısır',             dil: 'ar', para: 'EGP' },
  { slug: 'suudi-arabistan',ad: 'Suudi Arabistan',   dil: 'ar', para: 'SAR' },
  { slug: 'bae',            ad: 'BAE (Dubai)',       dil: 'ar', para: 'AED' },
  { slug: 'katar',          ad: 'Katar',             dil: 'ar', para: 'QAR' },
  { slug: 'kuveyt',         ad: 'Kuveyt',            dil: 'ar', para: 'KWD' },
  { slug: 'bahreyn',        ad: 'Bahreyn',           dil: 'ar', para: 'BHD' },
  { slug: 'umman',          ad: 'Umman',             dil: 'ar', para: 'OMR' },
  { slug: 'pakistan',       ad: 'Pakistan',          dil: 'ur', para: 'PKR' },
  { slug: 'hindistan',      ad: 'Hindistan',         dil: 'hi', para: 'INR' },
  { slug: 'bangladesh',     ad: 'Bangladeş',         dil: 'bn', para: 'BDT' },
  { slug: 'srilanka',       ad: 'Sri Lanka',         dil: 'si', para: 'LKR' },
  { slug: 'cin',            ad: 'Çin',               dil: 'zh', para: 'CNY' },
  { slug: 'japonya',        ad: 'Japonya',           dil: 'ja', para: 'JPY' },
  { slug: 'guney-kore',     ad: 'Güney Kore',        dil: 'ko', para: 'KRW' },
  { slug: 'tayvan',         ad: 'Tayvan',            dil: 'zh', para: 'TWD' },
  { slug: 'hong-kong',      ad: 'Hong Kong',         dil: 'zh', para: 'HKD' },
  { slug: 'singapur',       ad: 'Singapur',          dil: 'en', para: 'SGD' },
  { slug: 'malezya',        ad: 'Malezya',           dil: 'ms', para: 'MYR' },
  { slug: 'endonezya',      ad: 'Endonezya',         dil: 'id', para: 'IDR' },
  { slug: 'filipinler',     ad: 'Filipinler',        dil: 'tl', para: 'PHP' },
  { slug: 'tayland',        ad: 'Tayland',           dil: 'th', para: 'THB' },
  { slug: 'vietnam',        ad: 'Vietnam',           dil: 'vi', para: 'VND' },
  { slug: 'meksika',        ad: 'Meksika',           dil: 'es', para: 'MXN' },
  { slug: 'brezilya',       ad: 'Brezilya',          dil: 'pt', para: 'BRL' },
  { slug: 'arjantin',       ad: 'Arjantin',          dil: 'es', para: 'ARS' },
  { slug: 'kolombiya',      ad: 'Kolombiya',         dil: 'es', para: 'COP' },
  { slug: 'sili',           ad: 'Şili',              dil: 'es', para: 'CLP' },
  { slug: 'peru',           ad: 'Peru',              dil: 'es', para: 'PEN' },
  { slug: 'nijerya',        ad: 'Nijerya',           dil: 'en', para: 'NGN' },
  { slug: 'gana',           ad: 'Gana',              dil: 'en', para: 'GHS' },
  { slug: 'kenya',          ad: 'Kenya',             dil: 'sw', para: 'KES' },
  { slug: 'guney-afrika',   ad: 'Güney Afrika',      dil: 'en', para: 'ZAR' },
  { slug: 'fas',            ad: 'Fas',               dil: 'ar', para: 'MAD' },
  { slug: 'tunus',          ad: 'Tunus',             dil: 'ar', para: 'TND' },
  { slug: 'cezayir',        ad: 'Cezayir',           dil: 'ar', para: 'DZD' },
  { slug: 'libya',          ad: 'Libya',             dil: 'ar', para: 'LYD' },
  { slug: 'etiyopya',       ad: 'Etiyopya',          dil: 'am', para: 'ETB' },
  { slug: 'yeni-zelanda',   ad: 'Yeni Zelanda',      dil: 'en', para: 'NZD' },
];

// Türkiye dışı ülkeler için şehirler
export const ULKE_SEHIR: Record<string, string[]> = {
  almanya: ['berlin', 'hamburg', 'munih', 'koln', 'frankfurt', 'stuttgart', 'dusseldorf', 'leipzig'],
  fransa: ['paris', 'lyon', 'marsilya', 'toulouse', 'nice', 'nantes', 'strasbourg', 'bordeaux'],
  ingiltere: ['londra', 'birmingham', 'manchester', 'leeds', 'glasgow', 'liverpool', 'bristol'],
  abd: ['new-york', 'los-angeles', 'chicago', 'houston', 'phoenix', 'san-antonio', 'san-diego', 'dallas'],
  bae: ['dubai', 'abu-dabi', 'sarjah', 'ajman', 'ras-al-hayme'],
  suudi_arabistan: ['riyad', 'cidde', 'mekke', 'medine', 'dammam'],
  hollanda: ['amsterdam', 'rotterdam', 'lahey', 'utrecht', 'eindhoven'],
  belcika: ['bruksel', 'antwerp', 'gent', 'liege', 'brugge'],
  isvicre: ['zurich', 'cenevre', 'bern', 'basel', 'lozan'],
  ispanya: ['madrid', 'barselona', 'valensiya', 'sevilla', 'zaragoza', 'malaga'],
  italya: ['roma', 'milan', 'naples', 'turin', 'palermo', 'venedik'],
  rusya: ['moskova', 'st-petersburg', 'novosibirsk', 'yekaterinburg', 'kazan'],
  cin: ['pekin', 'shanghai', 'guangzhou', 'shenzhen', 'chengdu', 'wuhan'],
  hindistan: ['mumbai', 'delhi', 'bangalore', 'hyderabad', 'ahmedabad', 'chennai'],
  avustralya: ['sydney', 'melbourne', 'brisbane', 'perth', 'adelaide'],
  kanada: ['toronto', 'montreal', 'vancouver', 'calgary', 'ottawa'],
  japonya: ['tokyo', 'osaka', 'nagoya', 'sapporo', 'fukuoka', 'kyoto'],
};
